name: docker app

on:
  workflow_dispatch:

env:
  prefix: ${{github.actor}}${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
      - name: build the image
        run: |
          cd app-files
          docker build -t myapp .
      - name: docker push
        run: |
          echo "prefix=${{env.prefix}}" >> $GITHUB_ENV
          docker tag myapp ghcr.io/$prefix/vm-app/dev/doc-image:v1
          docker push ghcr.io/$prefix/vm-app/dev/doc-image:v1
